-- INSERT INTO USER
--     VALUES ('admin','$2a$04$Uny6iAmCcG1GpX8QG3lhOeJSz3lV/SB7et3CFr2ONvaKxZS5wNRqe','Vineet','Chauhan','admin@boxwarehouse.com','ROLE_ADMIN');
--
-- INSERT INTO USER
-- VALUES ('user','$2a$04$PnLviVXJ5rcVnu2Ud/i09OffcAZzKWHoDxdnr4JA8fD5Pyg2FkYaC','Charlie','Delta','user@boxwarehouse.com','ROLE_USER');
--
